-- ============================================================
-- FILE: 99_account_statements_table.sql
-- Creates the account_statements table for monthly bank
-- statements generated by the ETL pipeline.
-- Run this on the Aiven ledger_db BEFORE running statement_etl.py
-- ============================================================

USE ledger_db;

-- ────────────────────────────────────────────────
-- TABLE: ACCOUNT_STATEMENTS
-- Stores generated monthly statements per account.
-- ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS account_statements (
  statement_id     CHAR(36)        NOT NULL DEFAULT (UUID()),
  user_id          CHAR(36)        NOT NULL,
  account_id       CHAR(36)        NOT NULL,
  period_start     DATE            NOT NULL,
  period_end       DATE            NOT NULL,
  opening_balance  DECIMAL(18, 2)  NOT NULL,
  closing_balance  DECIMAL(18, 2)  NOT NULL,
  total_credits    DECIMAL(18, 2)  NOT NULL DEFAULT 0.00,
  total_debits     DECIMAL(18, 2)  NOT NULL DEFAULT 0.00,
  transaction_count INT            NOT NULL DEFAULT 0,
  line_items       JSON            NULL,        -- per-transaction detail with running balances
  generated_at     DATETIME        NOT NULL DEFAULT (UTC_TIMESTAMP()),

  PRIMARY KEY (statement_id),
  FOREIGN KEY (user_id)    REFERENCES users(user_id)       ON DELETE RESTRICT,
  FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE RESTRICT,

  -- Prevent duplicate statements for the same account + period
  UNIQUE KEY uq_account_period (account_id, period_start, period_end)
);

CREATE INDEX idx_stmt_user   ON account_statements (user_id);
CREATE INDEX idx_stmt_period ON account_statements (period_start, period_end);

SELECT 'account_statements table created successfully.' AS status;
